# Generated by Django 5.1.1 on 2024-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponceAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.TextField(max_length=500)),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RequestResponseAI',
                'verbose_name_plural': 'RequestResponseAI',
                'ordering': ['-created_at'],
            },
        ),
    ]
